#!/bin/bash

# Setting Time Limit (48 hours in seconds)
time_limit=$((48 * 60 * 60))

# Function to send team message
send_team_message() {
    DATE=$(date "+DATE: %d/%m/%y TIME: %H:%M:%S")
    Title="ALERT FROM $HOSTNAME"
    header="Content-Type: application/json"
    nav_slack_hook="https://prod-63.westus.logic.azure.com:443/workflows/2f13c0b9.../triggers/manual/paths/invoke?api-version=2016-06-01&..."

    generate_post_data=$(cat <<EOF
{
    "summary": "Card \"VS-Code_Session_Time_Notification\"",
    "themeColor": "0078D7",
    "title": "$Title",
    "sections": [
        {
            "activitySubtitle": "$DATE",
            "facts": [
                $session_details
            ],
            "text": "VS-Code sessions running for more than 48-hours."
        }
    ]
}
EOF
    )

    response=$(curl -s -o /dev/null -w "%{http_code}" -H "$header" --data "$generate_post_data" "$nav_slack_hook")
}

# Main script logic
output=$(ps -eo pid,etimes,user:20,%cpu,%mem,comm | grep -e vscode-session)
session_details=""

if [ -n "$output" ]; then
    while read -r line; do
        pid=$(echo "$line" | awk '{print $1}')
        etimes=$(echo "$line" | awk '{print $2}')
        userid=$(echo "$line" | awk '{print $3}')

        if [ "$etimes" -gt "$time_limit" ]; then
            session_details+=$(cat <<EOF
{
    "name": "User:",
    "value": "$userid"
},
{
    "name": "VS-code session ID:",
    "value": "$pid"
},
EOF
            )
        fi
    done <<< "$output"
    
    session_details=${session_details%,}

    if [ -n "$session_details" ]; then
        send_team_message
    fi
fi
